Models/ViewModel/SettingsViewModel.cs
namespace E_TutorApplicationFront.Models.ViewModel
{
    public class SettingsViewModel
    {
        public SettingInfoViewModel? SettingInfo { get; set; }
        public SosialProfile? SosialProfile { get; set; }
        public InstructorSettingsNotificationViewModel? NotificationViewModel { get; set; }
        public UpdatePasswordViewModel? UpdatePasswordInstructorViewModel { get; set;}
    }
}

Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using E_TutorApplicationFront.Models.ViewModel;
namespace E_TutorApplicationFront.Controllers
{
    public class InstructorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Dashboard()
        {
           // List<AsStudentViewModel> asStudentViewModel = new List<AsStudentViewModel>()
           // {
           //     new AsStudentViewModel { ActiveCourses = }
           // };
           //InstructorDashboardViewModel viewModel = new InstructorDashboardViewModel()
           //{
           //     AsStudentViews = 
           //};
            return View();
        }

        public IActionResult BasicInformationCreateCourse()
        {
            ViewBag.PageName = "Create a new course";
            return View();
        }

        public IActionResult AdvancedInformation()
        {
            ViewBag.PageName = "Create a new course";
            return View();
        }

        public IActionResult Settings()
        {
            SettingsViewModel settingsViewModel = new SettingsViewModel();

            SettingInfoViewModel viewModel = new SettingInfoViewModel()
            {
                FirstName = "shahla"
            };

            SosialProfile sosialProfile = new SosialProfile();

            InstructorSettingsNotificationViewModel notificationViewModel = new InstructorSettingsNotificationViewModel()
            {
                HowManyPeopleVisit = true,
                WhoBuyMyCourse = true,
            };

            settingsViewModel.SettingInfo = viewModel;
            settingsViewModel.SosialProfile = sosialProfile;
            settingsViewModel.NotificationViewModel = notificationViewModel;
            List<int> prefix = new List<int>()
            {
                994, 1, 10, 20, 40
            };

            ViewBag.Prefix = prefix;
            return View(settingsViewModel);
        }


        [HttpPost]
        public IActionResult SettingsInformationUpdate(SettingInfoViewModel settingInfoViewModel)
        {
            if (!ModelState.IsValid)
                return View("Settings");
            return RedirectToAction("Settings");
        }

        [HttpPost]
        public IActionResult SosialProfileUpdate(SosialProfile sosialProfile)
        {
            return RedirectToAction("Settings");
        }
    
        [HttpPost]
        public IActionResult NotificationSettingsUpdate(InstructorSettingsNotificationViewModel notificationSettingsNotificationViewModel)
        {
            return RedirectToAction("Settings");
        } 

        [HttpPost]
        public IActionResult UpdatePassword(UpdatePasswordViewModel updatePasswordInstructor)
        {
            if(!ModelState.IsValid)
                return View("Settings");
            return RedirectToAction("Settings");
        }

        public IActionResult MyCourses()
        {
            return View();
        }

        public IActionResult InstructorMyCourses(int page = 1)
        {
            return ViewComponent("InstructorMyCourses", new { page = page });
        }

        
        public IActionResult ViewCourseDetail(int courseId)
        {
            CourseDetailViewModel viewModel = new CourseDetailViewModel()
            {
                CourseId = courseId,
                CourseImgURL = "/images/instructor/coursethumbnail.svg",
                Title= "2021 Complete Python Bootcamp From Zero to Hero in Python",
                Description = "3 in 1 Course: Learn to design websites with Figma, build with Webflow, and make a living freelancing.",
                UploadedDate = DateTime.Now.AddMonths(-3).Date,
                LastUpdateDate = DateTime.Now.Date,
                CoursePrice = 13.99,
                CourseRating = 3.4,
                CourseRevenue = 131800455.82,
                Creators = new List<CourseCreators>()
                {
                    new CourseCreators{InstructorId = 1, InstructorName = "Kevin" , InstructorSurname = "Gilbert", InstructorImagUrl = "/images/instructor/kevin.svg"},
                    new CourseCreators{InstructorId = 2, InstructorName = "Kristin" , InstructorSurname = "Watson", InstructorImagUrl = "/images/instructor/gilbert.svg"}
                },
                CourseDetailedInfo = new CourseDetailedInformation
                {
                    AtachFile = 142,
                    AtachFileSize = 14.4, 
                    CourseLevel = "Beginner",
                    LectureCount = 1957,
                    LectureSize = 219.3,
                    TotalComments = 429,
                    StudentsEnrolled = 2023,
                    CourseLanguage = "Mandarin",
                    Hours = "19:37:51",
                    StudentsViewed = 42919
                } ,
                CourseRatings = new List<int> 
                {
                    4, 4, 2, 4, 3, 4, 3, 4, 2, 4, 3, 4, 4, 3, 4, 2, 4, 3, 4
                },
                Score = new CourseRatingScore
                {
                    Percentage1Star = 0,
                    Percentage2Star = 1,
                    Percentage3Star = 5,
                    Percentage4Star = 27,
                    Percentage5Star = 67
                }

            };


            return View(viewModel);
        }

        public void DeleteCourse(int courseId)
        {

        }

    }
}

ViewComponents/InstructorMyCoursesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using E_TutorApplicationFront.Models.Entities;
using E_TutorApplicationFront.Models.ViewModel;

namespace E_TutorApplicationFront.ViewComponents
{
    public class InstructorMyCoursesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int page = 1, int pageSize = 12)
        {

            List<CoursesViewModel> coursesList = new List<CoursesViewModel>()
            {
                   new CoursesViewModel{CourseId = 1, CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 2, CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 3,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 4,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 5,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 6,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 7,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 8,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 9,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 10,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 11,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 12,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 13,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 14,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 15,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 16,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 17,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 18,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 19,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 20,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 21, CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.2 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 22,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.3 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 23,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =4.5 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
                new CoursesViewModel{CourseId = 24,  CourseName = "Learn Python Programming Masterclass", CategoryName = "IT & Software", Rating =5.0 , StudentCount = "211,434", Price = 40, Url = "/images/CourseImages.svg"},
            };
            var paginatedCourses = coursesList.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = (int)Math.Ceiling((double)coursesList.Count / pageSize);

            return View(paginatedCourses);
        }
    }
}

Views/Instructor/AdvancedInformation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_InstructorLayout";
    ViewData["Title"] = "Create new course";
}
<div class="card mt-5">

    @Html.Partial("~/Views/Instructor/CreateANewCourseView.cshtml")
   <div class="card mt-4">

   </div>
</div>
<style>
 
</style>

Views/Instructor/BasicInformationCreateCourse.cshtml
@{
    Layout = "_InstructorLayout";
    ViewData["Title"] = "Create new course";
}
<div class="container mt-5">
@Html.Partial("~/Views/Instructor/CreateANewCourseView.cshtml")
    <div class="card mt-4 basicinformationform">
        <div class="card-body">
            <h5 class="card-title">Basic Information</h5>
            <form>
                <div class="form-group">
                    <label for="courseTitle">Title</label>
                    <input type="text" class="form-control" id="courseTitle" placeholder="Your course title" maxlength="80">
                </div>
                <div class="form-group">
                    <label for="courseSubtitle">Subtitle</label>
                    <input type="text" class="form-control" id="courseSubtitle" placeholder="Your course subtitle" maxlength="120">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="courseCategory">Course Category</label>
                        <select id="courseCategory" class="form-control">
                            <option selected>Select...</option>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="courseSubCategory">Course Sub-category</label>
                        <select id="courseSubCategory" class="form-control">
                            <option selected>Select...</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="courseTopic">Course Topic</label>
                    <input type="text" class="form-control" id="courseTopic" placeholder="What is primarily taught in your course?">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="courseLanguage">Course Language</label>
                        <select id="courseLanguage" class="form-control">
                            <option selected>Select...</option>
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="subtitleLanguage">Subtitle Language (Optional)</label>
                        <select id="subtitleLanguage" class="form-control">
                            <option selected>Select...</option>
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="courseLevel">Course Level</label>
                        <select id="courseLevel" class="form-control">
                            <option selected>Select...</option>
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="courseDuration">Duration</label>
                        <input type="text" class="form-control" id="courseDuration" placeholder="Course durations">
                    </div>
                </div>
               
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <button type="button" class="btn btn-secondary">Cancel</button>
                    </div>
                    <div class="form-group col-md-6 text-right">
                        <button type="submit" class="btn btn-primary">Save & Next</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    .basicinformationform {
        margin-top: 0px !important;
    }

    form label, form input{
        font-size: 14px;
    }

    .form-row{
        display: flex;
    }

    .form-control {
        border-radius: 0px !important;
        width: 90%;
        margin: 10px;
    }
</style>

Views/Instructor/Dashboard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_InstructorLayout";
    ViewData["Title"] = "Dashboard";
    ViewBag.PageName = "Dashboard";
}

<div class="container mt-sm-5">
    @Html.Partial("~/Views/Instructor/_CardDashboardPartialView.cshtml")
</div>

Views/Instructor/MyCourses.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.PageName = "My Courses";
    Layout = "_InstructorLayout";
    ViewData["Title"] = "My Courses";
}
<style>
    #myCoursesSearchBar {
        background-image: url('../images/magnifyingglass.svg');
        background-position: 8px 8px;
        background-repeat: no-repeat;
        background-size: 20px;
        font-size: 14px;
        padding: 8px 20px 8px 40px;
        border: none;
        width: 350px;
    }

    .coursesfilter{
        width: 86%;
        padding: 0px 20px ;
    }

        .coursesfilter col-2 {
            margin-right: 10px;
        }

    .dropdown{
        background-color: white;
        width: 90%;
    }
    .dropdown button{
        width: 100%;
    }

    .coursesfilter .col{
        margin-left: 15px;
    }

    .dropdown-toggle::after{
        margin-left: 80px;
    }

    .coursesfilter .col button{
        font-size: 14px;
    }

    .coursesfilter .col label{
        font-size: 10px;
        color: #4E5566;
    }
</style>
<div class="container mt-5 coursesfilter">
    <div class="row">
        <div class="col">
            <label>Search: </label>
            <div><input class="searchBar" type="text" id="myCoursesSearchBar" placeholder="Search in your courses..." /></div>
        </div>
        <div class="col">
            <label>Sort By:</label>
            <div class="dropdown">
                <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Latest
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">Option 1</a>
                    <a class="dropdown-item" href="#">Option 2</a>
                    <a class="dropdown-item" href="#">Option 3</a>
                </div>
            </div>
        </div>
         
        <div class="col"> 
            <label>Category: </label>
            <div class="dropdown">
                <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    All category
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">Option 1</a>
                    <a class="dropdown-item" href="#">Option 2</a>
                    <a class="dropdown-item" href="#">Option 3</a>
                </div>
            </div>
        </div>

        <div class="col"> 
            <label>Rating: </label>
            <div class="dropdown">
                <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    4 Star & Up
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">Option 1</a>
                    <a class="dropdown-item" href="#">Option 2</a>
                    <a class="dropdown-item" href="#">Option 3</a>
                </div>
            </div>
        </div>

    </div>

    <div class="row">

        @await Component.InvokeAsync("InstructorMyCourses", new { page = 1 })
    </div>
</div>

Views/Instructor/_NotificationPartialView.cshtml
@model InstructorSettingsNotificationViewModel

<div class="container mt-5 notificationdiv">
    <h5>Notifications</h5>
    <form asp-action="NotificationSettingsUpdate" asp-controller="Instructor">
        <div>
            <input type="checkbox" id="notifyPurchase" name="notifyPurchase" asp-for="WhoBuyMyCourse">
            <label for="notifyPurchase">I want to know who buy my course.</label>
        </div>
        <div>
            <input type="checkbox" id="notifyReview" name="notifyReview" asp-for="WhoWriteReviews">
            <label for="notifyReview">I want to know who write a review on my course.</label>
        </div>
        <div>
            <input type="checkbox" id="notifyComment" name="notifyComment" asp-for="WhoCommentedMyLecture">
            <label for="notifyComment">I want to know who commented on my lecture.</label>
        </div>
        <div>
            <input type="checkbox" id="notifyDownloadNotes" name="notifyDownloadNotes" asp-for="WhoDownloadMyLecture">
            <label for="notifyDownloadNotes">I want to know who download my lecture notes.</label>
        </div>
        <div>
            <input type="checkbox" id="notifyReply" name="notifyReply" asp-for="WhoRepliedMyComment">
            <label for="notifyReply">I want to know who replied on my comment.</label>
        </div>
        <div>
            <input type="checkbox" id="notifyProfileVisits" name="notifyProfileVisits" asp-for="HowManyPeopleVisit">
            <label for="notifyProfileVisits">I want to know daily how many people visited my profile.</label>
        </div>
        <div>
            <input type="checkbox" id="notifyDownloadAttachment" name="notifyDownloadAttachment" asp-for="WhoDownloadAttachFile">
            <label for="notifyDownloadAttachment">I want to know who download my lecture attach file.</label>
        </div>
        <button type="submit" id="submitsettingsinformation" class="btn btn-primary">Save Changes</button>

    </form>
</div>

Views/Instructor/_changePasswordPartialView.cshtml
@model UpdatePasswordInstructorViewModel

<div class="container mt-5 changepassword">
    <h5>Change Password</h5>
    <form asp-action="UpdatePassword" asp-controller="Instructor">
        <div class="mb-3">
            <label for="currentPassword" class="form-label">Current Password</label>
            <input type="password" class="form-control" id="currentPassword" placeholder="Password" asp-for="CurrentPassword">
            <span class="text-danger" asp-validation-for="CurrentPassword"></span>
        </div>
        <div class="mb-3">
            <label for="newPassword" class="form-label">New Password</label>
            <input type="password" class="form-control" id="newPassword" placeholder="Password" asp-for="NewPassword">
            <span class="text-danger" asp-validation-for="NewPassword"></span>
        </div>
        <div class="mb-3">
            <label for="confirmPassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm new password" asp-for="ConfirmPassword">
            <span class="text-danger" asp-validation-for="ConfirmPassword"></span>
        </div>
        <button type="submit" id="submitsettingsinformation" class="btn btn-primary">Save Changes</button>
    </form>

</div>

Views/Instructor/_settingsPartialView.cshtml
@model SettingInfoViewModel;
<div class="container mt-5 settings-container">
    <form asp-action="SettingsInformationUpdate" asp-controller="Instructor">
        <div class="row">
            <div class="col-md-9">
                <h5>Account Settings</h5>
                <div class="mb-3">
                    <label for="firstName" class="form-label">Full name</label>
                    <div class="row">
                        <div class="col">
                            <input type="text" class="form-control" id="firstName" placeholder="@(Model.FirstName ?? " Enter your firstname")" asp-for="FirstName">
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" id="lastName" placeholder="@(Model.LastName ?? " Enter your lastname")" asp-for="LastName"> 
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" class="form-control" id="username" placeholder="@(Model.LastName ?? " Enter your username")" asp-for="UserName">
                </div>
                <div class="mb-3">
                    <label for="phoneNumber" class="form-label">Phone Number</label>
                    <div class="phone-number-container">
                        
                        @if (ViewBag.Prefix != null)
                        {
                            <select class="country-code" asp-for="PhonePrefix">
                                @foreach (int i in ViewBag.Prefix)
                                {
                                    <option value="+@i" selected>+@i</option>
                                }
                            </select>
                        }
                        <input type="text" class="phone-number-input" placeholder="@(Model.PhoneNumber ?? " Your Phone number...")" asp-for="PhoneNumber">
                    </div>
                </div>


            </div>
            <div class="col-md-3">
                <div class="text-center">
                    <div class="mt-2 buttonandimage">
                        @* <button class="btn btn-outline-secondary">
                            <img src=@(Model.ProfileImageUrl ?? "https://via.placeholder.com/150") onclick="document.getElementById('profileImage').click();" class="" alt="Profile Photo">
                            Upload Photo
                        </button> *@
                        <input type="file" id="profileImage" name="ProfileImage" style="display: none;" onchange="document.getElementById('profileImageForm').submit()" asp-for="ProfileImageUrl">
                        <button type="button" class="btn btn-outline-secondary" onclick="document.getElementById('profileImage').click();">
                            <img src="@(Model.ProfileImageUrl ?? "https://via.placeholder.com/150")" class="" alt="Profile Photo">
                            Upload Photo
                        </button>
                    </div>
                    <small class="text-muted d-block">Image size should be under 1MB and image ratio needs to be 1:1</small>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" id="title" placeholder="@(Model.Tittle ?? " Your title, profession or small biography")" maxlength="50" asp-for="Tittle">
            </div>
            <div class="mb-3">
                <label for="biography" class="form-label">Biography</label>
                <textarea class="form-control" id="biography" rows="3" placeholder="@(Model.Biography ?? " Your title, profession or small biography")" asp-for="Biography"></textarea>
            </div>
            <button type="submit" id="submitsettingsinformation" class="btn btn-primary">Save Changes</button>
        </div>
    </form>
</div>

Views/Instructor/_sosialProfilePartialView.cshtml
@model SosialProfile

<div class="container mt-5 sosial-profile">
    <form asp-action="SosialProfileUpdate" asp-controller="Instructor">
        <div class="row">
            <h5>Sosial profile</h5>
        </div>
        <div class="row">
            <div class="mb-3">
                <label>Personal Website</label>
                <div class="input-container">
                    <img src="~/images/globe.svg" />
                    <input type="text" class="" placeholder="@(Model.PersonalWebsiteLink ?? " Personal website or portfolio url...")" asp-for="PersonalWebsiteLink">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="mb-3">
                <div class="row disposedcols">
                    <div class="col">
                        <label for="facebook" class="form-label">Facebook</label>
                        <div class="input-container">
                            <img src="~/images/instructor/facebook.svg" />
                            <input type="text" class="form-control" id="facebookusername" placeholder="@(Model.FacebookUserName ?? "Username")" asp-for="FacebookUserName">
                        </div>
                    </div>
                    <div class="col">
                        <label for="facebook" class="form-label">Instagram</label>
                        <div class="input-container">
                            <img src="~/images/instructor/instagram.svg" />
                            <input type="text" class="form-control" id="instagramusername" placeholder="@(Model.InstagramUserName ?? "Username")" asp-for="InstagramUserName">
                        </div>
                    </div>
                    <div class="col">
                        <label for="facebook" class="form-label">Linkedin</label>
                        <div class="input-container">
                            <img src="~/images/instructor/linkedin.svg" />
                            <input type="text" class="form-control" id="linkedinusername" placeholder="@(Model.LinkedinUserName ?? "Username")" asp-for="LinkedinUserName">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="mb-3">
                <div class="row disposedcols">
                    <div class="col">
                        <label for="facebook" class="form-label">X</label>
                        <div class="input-container">
                            <img src="~/images/instructor/twitter.svg" />
                            <input type="text" class="form-control" id="twitterusername" placeholder="@(Model.XUserName ?? "Username")" asp-for="XUserName">
                        </div>
                    </div>
                    <div class="col">
                        <label for="facebook" class="form-label">Whatsapp</label>
                        <div class="input-container">
                            <img src="~/images/instructor/whatsapp.svg" />
                            <input type="text" class="form-control" id="whatsappusername" placeholder="@(Model.WhatsappUserName ?? "Username")" asp-for=" WhatsappUserName"> 
                        </div>
                    </div>
                    <div class="col">
                        <label for="facebook" class="form-label">Youtube</label>
                        <div class="input-container">
                            <img src="~/images/instructor/youtube.svg" />
                            <input type="text" class="form-control" id="youtubeusername" placeholder="@(Model.YoutubeUserName ?? "Username")" asp-for="YoutubeUserName">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <button type="submit" id="submitsettingsinformation" class="btn btn-primary">Save Changes</button>

        </div>

    </form>
</div>