Models/ViewModel/Student.cs
namespace E_TutorApplicationFront.Models.ViewModel
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Speciality { get; set; }
    }
}

Models/ViewModel/StudentDashboardViewModel.cs
namespace E_TutorApplicationFront.Models.ViewModel
{
    public class StudentDashboardViewModel
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int EnrolledCoursesCount { get; set; }
        public int ActiveCoursesCount { get; set; }
        public int ComplitedCoursesCount { get; set; }
        public int CourseInstructorCount { get; set; }
     
    }
}

Models/ViewModel/StudentTeachersViewModel.cs
namespace E_TutorApplicationFront.Models.ViewModel
{
    public class StudentTeachersViewModel
    {
        public int Id { get; set; }
        public string TeacherFullname { get; set; }
        public string TeacherSpecialty { get; set; }
        public string TeacherImgPath{ get; set; }
        public int StudentsCount{ get; set; }
        public double TeacherPoint{ get; set; }
        
    }
}

Models/ViewModel/StudentWishListViewModel.cs
namespace E_TutorApplicationFront.Models.ViewModel
{
    public class StudentWishListViewModel
    {
        public int Id { get; set; }
        public string? ImgPath { get; set; }
        public List<InstructorsList>? Instructors { get; set; }
        public double StarPoint { get; set; }
        public decimal Price { get; set; }
        public string? CourseName { get; set; }
    }

    public class InstructorsList
    {
        public int Id { get; set; }
        public string? InstructorFullName { get; set; }
    }
}

Controllers/StudentController.cs
using E_TutorApplicationFront.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Drawing.Printing;

namespace E_TutorApplicationFront.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult StudentDashboard() 
        {
            StudentDashboardCardsViewModel model = new StudentDashboardCardsViewModel()
            {
                EnrolledCoursesCount = 957,
                ActiveCoursesCount = 6,
                COmplitedCoursesCount = 951,
                CourseInstructorCount = 241
            };

            return View(model);
        }

       

        public IActionResult StudentWishList()
        {
            var model = new List<StudentWishListViewModel>()
            {
                new StudentWishListViewModel {Id = 1, ImgPath= "/images/studentcourseimages/courseimg46.svg", CourseName = "The Ultimate Drawing Course - Beginner to Advanced", Price = 37, StarPoint = 4.6,  Instructors = new List<InstructorsList>(){ new InstructorsList { InstructorFullName = "Harry Potter" },new InstructorsList { InstructorFullName = "John Wick" },  } }, 
                new StudentWishListViewModel {Id = 2, ImgPath= "/images/studentcourseimages/courseimg48.svg", CourseName = "Digital Marketing Masterclass - 23 Courses in 1", Price = 24, StarPoint = 4.8,  Instructors = new List<InstructorsList>(){ new InstructorsList { InstructorFullName = "Nobody" } } }, 
                new StudentWishListViewModel {Id = 3, ImgPath= "/images/studentcourseimages/courseimg47.svg", CourseName = "Angular - The Complete Guide (2021 Edition)", Price = 13, StarPoint = 4.7,  Instructors = new List<InstructorsList>(){ new InstructorsList { InstructorFullName = "Nobody" } } }
            }; 

            return View(model); 
        }

        public IActionResult StudentSettings()
        {
            
            var model = new StudentBioInformation()
            {
                Name = "Moony",
                Surname = "Xristo",
                Email = "Moony@gmail.com",
                Username = "moon1234",
                UpdatePasswordViewModel = null
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult ChangeStudentPassword(UpdatePasswordViewModel updateStudentPassword)
        {
            if (!ModelState.IsValid)
                return View("StudentSettings", updateStudentPassword);
            return RedirectToAction("StudentSettings");
        }

        [HttpPost]
        public IActionResult ChangeStudentBioInformation(StudentBioInformation studentBioInformation)
        {
            
            return View();
        }
        public IActionResult StudentCourses(int page = 1, int pageSize = 12)
        {
            var courses = new List<StudentCoursesViewModel>()
            {
                new StudentCoursesViewModel() {CourseId =1, CourseName = "Learn More About Web Design", CourseImgUrl = "", CourseSectionName = "Learn Ethical Hacking From Scratch", CourseWatchPercentage = 0, IsStart = false},
                new StudentCoursesViewModel() {CourseId =2, CourseName = "Font Properties Challenge 3", CourseImgUrl = "", CourseSectionName = "SQL for NEWBS: Weekender Crash Course", CourseWatchPercentage = 2, IsStart = true},
                new StudentCoursesViewModel() {CourseId =3, CourseName = "Adding Content to Our Website", CourseImgUrl = "", CourseSectionName = "Complete Adobe Lightroom Megacourse: Begin...", CourseWatchPercentage = 0, IsStart = false},
                new StudentCoursesViewModel() {CourseId =4, CourseName = "CSS Font Property Challenge Solution", CourseImgUrl = "", CourseSectionName = "Machine Learning A-Z™: Hands-On Python & R I...", CourseWatchPercentage = 23, IsStart = true},
                new StudentCoursesViewModel() {CourseId =5, CourseName = "Adding Content to Our Website", CourseImgUrl = "", CourseSectionName = "Premiere Pro CC for Beginners: Video Editing in...", CourseWatchPercentage = 26, IsStart = true},
                new StudentCoursesViewModel() {CourseId =6, CourseName = "The Dark Art of Centering Elements w...", CourseImgUrl = "", CourseSectionName = "Graphic Design Masterclass - Learn GREAT De...", CourseWatchPercentage = 21, IsStart = true},
                new StudentCoursesViewModel() {CourseId =7, CourseName = "CSS Static and Relative Positioning", CourseImgUrl = "", CourseSectionName = "Angular - The Complete Guide (2021 Edition)", CourseWatchPercentage = 0, IsStart = false},
                new StudentCoursesViewModel() {CourseId =8, CourseName = "Learn More About Typography", CourseImgUrl = "", CourseSectionName = "Complete Blender Creator: Learn 3D Modelling...", CourseWatchPercentage = 52, IsStart = true},
                new StudentCoursesViewModel() {CourseId =1, CourseName = "Learn More About Web Design", CourseImgUrl = "", CourseSectionName = "Learn Ethical Hacking From Scratch", CourseWatchPercentage = 0, IsStart = false},
                new StudentCoursesViewModel() {CourseId =2, CourseName = "Font Properties Challenge 3", CourseImgUrl = "", CourseSectionName = "SQL for NEWBS: Weekender Crash Course", CourseWatchPercentage = 2, IsStart = true},
                new StudentCoursesViewModel() {CourseId =3, CourseName = "Adding Content to Our Website", CourseImgUrl = "", CourseSectionName = "Complete Adobe Lightroom Megacourse: Begin...", CourseWatchPercentage = 0, IsStart = false},
                new StudentCoursesViewModel() {CourseId =4, CourseName = "CSS Font Property Challenge Solution", CourseImgUrl = "", CourseSectionName = "Machine Learning A-Z™: Hands-On Python & R I...", CourseWatchPercentage = 23, IsStart = true},
                new StudentCoursesViewModel() {CourseId =5, CourseName = "Adding Content to Our Website", CourseImgUrl = "", CourseSectionName = "Premiere Pro CC for Beginners: Video Editing in...", CourseWatchPercentage = 26, IsStart = true},
                new StudentCoursesViewModel() {CourseId =6, CourseName = "The Dark Art of Centering Elements w...", CourseImgUrl = "", CourseSectionName = "Graphic Design Masterclass - Learn GREAT De...", CourseWatchPercentage = 21, IsStart = true},
                new StudentCoursesViewModel() {CourseId =7, CourseName = "CSS Static and Relative Positioning", CourseImgUrl = "", CourseSectionName = "Angular - The Complete Guide (2021 Edition)", CourseWatchPercentage = 0, IsStart = false},
                new StudentCoursesViewModel() {CourseId =8, CourseName = "Learn More About Typography", CourseImgUrl = "", CourseSectionName = "Complete Blender Creator: Learn 3D Modelling...", CourseWatchPercentage = 52, IsStart = true},
                new StudentCoursesViewModel() {CourseId =9, CourseName = "Introductions", CourseImgUrl = "", CourseSectionName = "Ultimate Google Ads Training 2020: Profit with...", CourseWatchPercentage = 0, IsStart = false},
            };
            var pagedCourses = courses.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.TotalPages = Math.Ceiling((double)courses.Count() / pageSize);
            ViewBag.CurrentPage = page;

            return View(pagedCourses);
        }
        public IActionResult StudentTeachers(int page = 1, int pageSize = 12)
        {
            var teachers = new List<StudentTeachersViewModel>()
            {
                new StudentTeachersViewModel(){Id = 1,TeacherFullname = "Wade Warren", StudentsCount = 20, TeacherPoint = 5.0, TeacherSpecialty = "Digital Product Designer"},
                new StudentTeachersViewModel(){Id = 2,TeacherFullname = "Bessie Cooper", StudentsCount = 568, TeacherPoint = 4.5, TeacherSpecialty = "Senior Developer"},
                new StudentTeachersViewModel(){Id = 3,TeacherFullname = "Floyd Miles", StudentsCount = 568, TeacherPoint = 4.5, TeacherSpecialty = "UI/UX Designer"},
                new StudentTeachersViewModel(){Id = 4,TeacherFullname = "Ronald Richards", StudentsCount = 435, TeacherPoint = 5, TeacherSpecialty = "Lead Developer"},
                new StudentTeachersViewModel(){Id = 5,TeacherFullname = "Devon Lane", StudentsCount = 435, TeacherPoint = 4.0, TeacherSpecialty = "Senior Developer"},
                new StudentTeachersViewModel(){Id = 6,TeacherFullname = "Robert Fox", StudentsCount = 356, TeacherPoint = 4.5, TeacherSpecialty = "UI/UX Designer"},
                new StudentTeachersViewModel(){Id = 7,TeacherFullname = "Kathryn Murphy", StudentsCount = 356, TeacherPoint = 5.0, TeacherSpecialty = "Adobe Instructor"},
                new StudentTeachersViewModel(){Id = 8,TeacherFullname = "Jerome Bell", StudentsCount = 711, TeacherPoint = 5.0, TeacherSpecialty = "Adobe Instructor"},
            };
            var pagedTeachers = teachers.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.TotalPages = Math.Ceiling((double)teachers.Count() / pageSize);
            ViewBag.CurrentPage = page;

            return View(pagedTeachers);
        }

    }
}

ViewComponents/StudentCoursesViewComponent.cs
using E_TutorApplicationFront.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
namespace E_TutorApplicationFront.ViewComponents
{
    public class StudentCoursesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<StudentCoursesViewModel> courselist = new List<StudentCoursesViewModel>()
            {
                new StudentCoursesViewModel {CourseId = 1, CourseName = "Reiki Level I, II and Master/Teacher Program", CourseSectionName = "1. Intorductions" , CourseWatchPercentage = 0, CourseImgUrl = "/images/CourseImages.svg"},
                new StudentCoursesViewModel {CourseId = 1, CourseName = "Reiki Level I, II and Master/Teacher Program", CourseSectionName = "1. Intorductions" , CourseWatchPercentage = 0, CourseImgUrl = "/images/CourseImages.svg"},
                new StudentCoursesViewModel {CourseId = 1, CourseName = "Reiki Level I, II and Master/Teacher Program", CourseSectionName = "1. Intorductions" , CourseWatchPercentage = 0, CourseImgUrl = "/images/CourseImages.svg"},
                new StudentCoursesViewModel {CourseId = 1, CourseName = "Reiki Level I, II and Master/Teacher Program", CourseSectionName = "1. Intorductions" , CourseWatchPercentage = 0, CourseImgUrl = "/images/CourseImages.svg"},
                new StudentCoursesViewModel {CourseId = 1, CourseName = "Reiki Level I, II and Master/Teacher Program", CourseSectionName = "1. Intorductions" , CourseWatchPercentage = 0, CourseImgUrl = "/images/CourseImages.svg"},
                new StudentCoursesViewModel {CourseId = 1, CourseName = "Reiki Level I, II and Master/Teacher Program", CourseSectionName = "2. Students" , CourseWatchPercentage = 0, CourseImgUrl = "/images/CourseImages.svg"},
            };

            return View(courselist);
        }
    }
}

Views/Student/Index.cshtml
@{
    Layout = "_StudentLayout";
}

Views/Student/StudentCourses.cshtml
@{
    Layout = "_StudentLayout";
}
<style>
    .studentCoursesSearch{
        padding-bottom: 20px;
        display: inline-block;
    }

    .results .searchBar{
        width: 100% !important;
    }
    .results .dropdown{
        padding-top: 10px;
    }
</style>
<div class="results">
    <div class="row">
        <div class="col col-6">
            <span class="studentCoursesSearch">Search</span> <br />
           
        </div>
        <div class="col col-3"> 
            <span class="studentCoursesSearch">Sort by:</span> <br />
           
        </div>
        <div class="col col-3"> 
            <span class="studentCoursesSearch">Teacher:</span> <br />
           
        </div>

    </div>
    <div class="row">
        <div class="col col-6">
           
            <input class="searchBar" type="text" id="searchBar" placeholder="What do you want learn..." />
        </div>
        <div class="col col-3">
            
            <div class="dropdown" style="margin-right: 20px; border: 1px solid #E9EAF0; padding: 8px;">
                <select name="Latest" id="browse" style="font-size: 14px; padding: 0px 40px 2px 0px;">
                    <option value="">Latest</option>
                </select>
            </div>
        </div>
        <div class="col col-3">
            
            <div class="dropdown" style="margin-right: 20px; border: 1px solid #E9EAF0; padding: 8px;">
                <select name="browse" id="browse" style="font-size: 14px; padding: 0px 40px 2px 0px;">
                    <option value="">All Teachers</option>
                </select>
            </div>
        </div>
    </div>
</div>

Views/Student/StudentDashboard.cshtml
@model StudentDashboardCardsViewModel;
@{
    Layout = "_StudentLayout";
}

<style>
    .dashboadrBody {
        display: flex;
        flex-wrap: nowrap;
        gap: 20px;
    }

        .dashboadrBody .card {
            padding: 5px;
            border: none;
            border-radius: 0px;
            width: 300px;
            padding: 15px;
        }

        .dashboadrBody .card {
            display: flex;
            flex-wrap: nowrap;
            flex-direction: row;
        }

        .dashboadrBody .content h2 {
            font-size: 16px;
            font-weight: 500;
        }

        .dashboadrBody .content p {
            font-size: 12px;
            color: #4E5566;
        }

        .dashboadrBody img {
            padding-right: 20px;
        }

    .results {
        width: 100%;
    }

        .results h5, .enrolledCourses h5 {
            padding: 25px 0px 20px 0px;
            font-weight: 600;
        }

    #courseCarousel{
        padding-top: 30px;
    }
</style>
<div class="results">
    <h5>Dashboard</h5>
    <div class="dashboadrBody">
        <div class="card" style="background-color: #FFEEE8;">
            <div class="icon">
                <img src="~/images/enrolledcourse.svg" />
            </div>
            <div class="content">
                <h2>@Model.EnrolledCoursesCount</h2>
                <p>Enrolled Courses</p>
            </div>
        </div>
        <div class="card " style="background-color: #EBEBFF;">
            <div class="icon">
                <img src="~/images/activecourse.svg" />
            </div>
            <div class="content">
                <h2>@Model.ActiveCoursesCount</h2>
                <p>Active Courses</p>
            </div>
        </div>
        <div class="card" style="background-color: #E1F7E3;">
            <div class="icon">
                <img src="~/images/complitedcourse.svg" />
            </div>
            <div class="content">
                <h2>@Model.COmplitedCoursesCount</h2>
                <p>Complited Courses</p>
            </div>
        </div>
        <div class="card" style="background-color: #FFF2E5;">
            <div class="icon">
                <img src="~/images/courseinstructor.svg" />
            </div>
            <div class="content">
                <h2>@Model.CourseInstructorCount</h2>
                <p>Course Instructors</p>
            </div>
        </div>
    </div>
</div>


<div id="courseCarousel" class="carousel slide">
    <div class="row">

        <div class="col col-sm-6">
            <h5><b>Let’s start learning, Kevin</b></h5>
        </div>
        <div class="col col-sm-6 caruselbuttons">
            <div class="carousel-controls">
                <button class="carousel-control-btn" id="prevBtn" data-target="#courseCarousel" data-slide="prev">
                    <img src="~/images/arrowleft.svg" />

                </button>
                <button class="carousel-control-btn" id="nextBtn" data-target="#courseCarousel" data-slide="next">
                    <img src="~/images/arrowright.svg" />

                </button>
            </div>
        </div>


    </div>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="row">
                @await Component.InvokeAsync("StudentCourses")
            </div>
        </div>
    </div>

</div>

Views/Student/StudentSettings.cshtml
@model StudentBioInformation?
@{
    Layout = "_StudentLayout";
}
<style>
    .buttonandimage {
        display: flex;
        flex-wrap: nowrap;
        flex-direction: column;
        width: 100%;
        padding: 40px 25px;
        margin-left: auto;
        margin-right: auto;
    }

    .text-center {
        background-color: white;
        margin-right: 50px;
        border: 1px solid #E9EAF0;
    }

        .text-center small {
            margin-top: 0px;
            font-size: 10px;
            padding: 3px 15px;
        }

        .text-center button {
            border: none;
            padding: 3px;
            width: 250px;
        }

            .text-center button:hover {
                border: none;
                background-color: #F5F7FA;
            }

    .input-container {
        display: flex;
        align-items: center;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        width: 80%;
    }

        .input-container img {
            font-size: 20px;
            color: #FF6636;
            margin-right: 8px;
            width: 17px;
        }

        .input-container input {
            width: 100%;
            border: none;
            outline: none;
            font-size: 16px;
            border-left: 2px solid #E9EAF0;
            padding: 1px;
            margin-left: 0px !important;
        }

            .input-container input::placeholder {
                color: #bbb;
            }

    .textboxCol input, .textboxCol text, .changepassword input{
        width: 100%;
        font-size: 14px;
        padding: 10px;
        border: 1px solid #E9EAF0;
        border-radius: 0;
        margin: 5px 0px 10px 0px;
    }

    .textboxCol span, .changepassword span, .changepassword label{
        font-size: 12px;
    }
    ::placeholder{
        color: #8C94A3;
    }

    #SaveChanges{
        color: white;
        background-color: #FF6636;
        border: none;
        padding: 5px 15px;
        margin-top: 18px;
        border-radius: 0px;
    }

    .changepassword{
        padding: 0px;
    }
</style>

<div class="results">
    <h5>Account settings</h5>

    <form asp-action="ChangeStudentBioInformation" asp-controller="Student">
        <div class="row">
            <div class=" col col-md-4">
                <div class="text-center">
                    <div class="mt-2 buttonandimage">
                       
                        <input type="file" id="profileImage" name="ProfileImage" style="display: none;" onchange="document.getElementById('profileImageForm').submit()" asp-for="ImgPath">
                        <button type="button" class="btn btn-outline-secondary" onclick="document.getElementById('profileImage').click();">
                            <img src="@(Model?.ImgPath ?? "https://via.placeholder.com/220")" class="" alt="Profile Photo">
                            Upload Photo
                        </button>
                    </div>
                    <small class="text-muted d-block">Image size should be under 1MB and image ratio needs to be 1:1</small>
                </div>
            </div>
            <div class="col col-8 textboxCol">
                <div class="row">
                    <div class="col">
                        <span>Full Name</span><br />
                        <input type="text" placeholder="@(Model?.Name?? "Name ")" asp-for="Name"/>
                    </div>
                    <div class="col">
                        <br />
                        <input type="text" placeholder="@(Model?.Surname?? "Surname ")" asp-for="Surname" />
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <span>Username</span><br />
                        <input type="text" placeholder="@(Model?.Username?? "Enter your username ")" asp-for="Username" />
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <span>Email</span><br />
                        <input type="email" placeholder="@(Model?.Email?? "Email Address ")" asp-for="Email" />
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <span>Tittle</span><br />
                        <textarea class="form-control" type="text" placeholder="@(Model?.Title ?? "Your title, profession or small biography" )" asp-for="Title"/></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <button id="SaveChanges">Save Changes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
   

    <div class="row">
        <div class="col col-6">
            @Html.Partial("_changeStudentPasswordPartialView", Model.UpdatePasswordViewModel)
        </div>
    </div>
</div>

Views/Student/StudentWishList.cshtml
@model List<StudentWishListViewModel>?
@{
    Layout = "_StudentLayout";
    int? countEl = Model?.Count;
    
}

<style>
    .wishListTableMain{
        border: 1px solid #E9EAF0;
    }
    .wishListTableHeader{
        padding: 10px;
        color: #4E5566;
        font-size: 12px;
        font-weight: 500;
        width: 100%;
        border-bottom: 1px solid #E9EAF0;
    }



    .wishListTableMain .row{
        margin: 5px;

    }

  

    .wishListTable img{
        padding: 3px 0px;
    }
    #courseName{
        color: #1D2026;
        font-size: 15px;
        font-weight: 600;
    }

    #StarPoint{
        color: #1D2026;
        font-size: 12px;
    }

    
    #CourseInstructor{
        color: #4E5566;

    }

    #CourseInstructorCourseBy{
        color: #A1A5B3;
    }

    .courseNameclass{
        margin-bottom: 20px;
    }

    #priceSpan{
        color: #FF6636;
        display: inline-block;
        margin-top: 35%;
    }

    .buyNow, .addToCart, .wishButton {
        margin-top: 35%;
        border: none;
        font-size: 13px;
    }

    .buyNow, .addToCart {
        width: 120px;
        height: 40px;
        font-weight: 600;
    }

    .addToCart{
        color: white;
        background-color: #FF6636;
        font-weight: 500!important;
    }
    
    #wishImg, .wishButton {
        width:42px;
        height: 42px;
        background-color: transparent;
        margin-top: 63%;
    }

    .linefortable{
        width: 96.2%;
        height: 1px;
        margin: 1px auto 15px auto;
        border-top: 2px solid #d8d9e3;
        color: #d8d9e3;
    }

    .imageCol{
        padding: 0px;
    }
</style>

<div  class="results">

    <h5>Wishlist</h5>
    <div class=" wishListTableMain">
        <div class="row wishListTableHeader">
            <div class="col col-6">
                <span>COURSE</span>
            </div>
            <div class="col col-2">
                <span>PRICES</span>
            </div>
            <div class="col col-4">
                <span>ACTION</span>
            </div>
        </div>
        @if (Model is not null)
        {
            <div class="wishListTableBody">

                @foreach (var item in Model)
                {
                    <div class="row mainRowInBody">
                        <div class="col col-6">
                            <div class="row">
                                <div class="col col-4 imageCol">
                                    <img src=@item.ImgPath width="150" />
                                </div>
                                <div class="col col-8">
                                    <div>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="23" height="23">
                                            <polygon points="50,15 61,35 84,35 66,50 71,72 50,60 29,72 34,50 16,35 39,35" fill="orange" />
                                        </svg>
                                        <span id="StarPoint"><b>@item.StarPoint</b></span>
                                    </div>
                                    <div class="courseNameclass">
                                        <p id="courseName">@item.CourseName</p>
                                    </div>
                                    <div class="bottomName">
                                        <p id="CourseInstructor">
                                            <span id="CourseInstructorCourseBy">Course By: </span>
                                            @{
                                                int? s = item.Instructors.Count;
                                            }
                                            @foreach (var i in item.Instructors)
                                            {
                                                @i.InstructorFullName
                                                if (s > 1)
                                                {
                                                    <span>•</span>
                                                }

                                                s -= 1;

                                            }

                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col col-2 " style="text-align: center">
                            <span id="priceSpan">$@item.Price</span>
                        </div>
                        <div class="col col-4">
                            <div class="row">
                                <div class="col col-5">
                                    <button class="buyNow">Buy Now</button>
                                </div>
                                <div class="col col-5">
                                    <button class="addToCart">Add To Cart</button>

                                </div>
                                <div class="col col-2">
                                    <button class="wishButton"><img id="wishImg" src="~/images/student/button.svg" /></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    countEl -= 1;
                    if (countEl > 0)
                    {
                        <hr class="linefortable" />
                    }
                }
            </div>
        }
        else
        {
            <div style="text-align: center;">

                <h5>Wishlist is empty</h5>
            </div>
        }


    </div>
</div>

Views/Student/_StudentDashboardMain.cshtml
<div class="container linksAndResults">
    <partial action="StudentDashboard"></partial>
    @Html.Partial("_StudentDashboard")
</div>

<div class="container linksAndResults coursesSection">
    <div id="courseCarousel" class="carousel slide">
        <div class="row">

            <div class="col col-sm-6">
                <h4><b>Let’s start learning, Kevin</b></h4>
            </div>
            <div class="col col-sm-6 caruselbuttons">
                <div class="carousel-controls">
                    <button class="carousel-control-btn" id="prevBtn" data-target="#courseCarousel" data-slide="prev">
                        <img src="~/images/arrowleft.svg" />

                    </button>
                    <button class="carousel-control-btn" id="nextBtn" data-target="#courseCarousel" data-slide="next">
                        <img src="~/images/arrowright.svg" />

                    </button>
                </div>
            </div>


        </div>

        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="row">
                    @await Component.InvokeAsync("StudentCourses")
                </div>
            </div>
        </div>

    </div>
</div>

Views/Student/_changeStudentPasswordPartialView.cshtml
@model UpdatePasswordViewModel

<div class="container mt-5 changepassword">
    <h5>Change Password</h5>
    <form asp-action="ChangeStudentPassword" asp-controller="Student">
        <div class="mb-3">
            <label for="currentPassword" class="form-label">Current Password</label>
            <input type="password" class="form-control" id="currentPassword" placeholder="Password" asp-for="CurrentPassword">
            <span class="text-danger" asp-validation-for="CurrentPassword"></span>
        </div>
        <div class="mb-3">
            <label for="newPassword" class="form-label">New Password</label>
            <input type="password" class="form-control" id="newPassword" placeholder="Password" asp-for="NewPassword">
            <span class="text-danger" asp-validation-for="NewPassword"></span>
        </div>
        <div class="mb-3">
            <label for="confirmPassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm new password" asp-for="ConfirmPassword">
            <span class="text-danger" asp-validation-for="ConfirmPassword"></span>
        </div>
        <button type="submit" id="SaveChanges" class="btn">Save Changes</button>
    </form>

</div>